#!/bin/sh

# Prints the current volume or ﱝ if muted.

[ $(pamixer --get-mute) = true ] && echo "ﱝ mute" && exit


vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="墳"

elif [ "$vol" == "0" ]; then
    icon="ﱝ"

elif [ "$vol" -lt "30" ]; then
	icon="奄"


else
	icon="奔"

fi

echo "$icon $vol%"
