#! /bin/sh
bspc -r "*"

### AUTOSTART

killall picom; picom -b &
nitrogen --restore
lxpolkit &
/usr/lib/xfce4/notifyd/xfce4-notifyd &

killall redshift; killall redshift-gtk; redshift-gtk &    	 

# Uncomment if you have a system tray enabled
# killall nm-applet; nm-applet &
# killall blueman-applet; blueman-applet &
# killall pamac-tray; pamac-tray &
# killall protonvpn-tray; protonvpn-tray &


# POLYBAR
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX 
# bspc monitor -d           

bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false

bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

## COLORS
bspc config active_border_color           "#03b2bf"
bspc config focused_border_color          "#03b2bf"
bspc config normal_border_color           "#666666"  
bspc config presel_feedback_color         "#ff5f5f"

bspc config click_to_focus                none
bspc config focus_follows_pointer         true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner



# RULES

## Floating windows

# defaults
bspc rule -a *:confirm state=floating
bspc rule -a *:dialog state=floating
bspc rule -a *:download state=floating
bspc rule -a *:error state=floating
bspc rule -a *:file_progress state=floating
bspc rule -a *:notification state=floating
bspc rule -a *:splash state=floating
bspc rule -a *:toolbar state=floating
bspc rule -a *:confirmreset state=floating
bspc rule -a *:makebranch state=floating
bspc rule -a *:maketag state=floating
bspc rule -a *:branchdialog state=floating
bspc rule -a *:pinentry state=floating
bspc rule -a *:ssh-askpass state=floating

# mine
bspc rule -a *:lxpolkit state=floating
bspc rule -a *:*:'Picture in picture' state=floating
bspc rule -a *:Steam state=floating
bspc rule -a *:pavucontrol state=floating
bspc rule -a *:pamix state=floating 
bspc rule -a *:Float state=floating
bspc rule -a *:emacs state=tiled



## Send-to-desktop rules

# Browsers
bspc rule -a *:Navigator desktop='^1' follow=on
bspc rule -a *:qutebrowser desktop='^1' follow=on
bspc rule -a *:vivaldi-snapshot desktop='^1' follow=on
bspc rule -a *:brave-browser desktop='^1' follow=on
bspc rule -a *:chromium desktop='^1' follow=on

# Virtualization
bspc rule -a *:virt-manager desktop='^6' follow=on
bspc rule -a *:'VirtualBox Manager' desktop='^6' follow=on

# Games
bspc rule -a *:Steam desktop='^5' follow=on
bspc rule -a *:*:TLauncher desktop='^5' follow=on
bspc rule -a *:*:'TLauncher 2.74' desktop='^5' follow=on

# Music
bspc rule -a *:mocp desktop='^4' follow=on
bspc rule -a *:castero desktop='^4' follow=on
bspc rule -a *:vocal desktop='^4' follow=on
bspc rule -a *:pragha desktop='^4' follow=on
bspc rule -a *:Spotify desktop='^4' follow=on






