#! /usr/bin/bash
bspc -r "*"

### AUTOSTART

# Set keyboard repeat delay
xset r rate 150 40

# Set compose key
setxkbmap -option compose:ralt
setxkbmap -option caps:swapescape

# touchegg for touchpad gestures
# touchegg &

# picom &
nitrogen --restore                                                      # wallpaper
$HOME/.config/polybar/launch.sh                                         # polybar
pidof lxpolkit || /usr/lib/lxpolkit/lxpolkit &                          # policy kit
dunst &                                                                 # notifications
# emacs --daemon &                                                      # emacs daemon
xss-lock -- betterlockscreen -s &                                       # screensaver
# killall redshift; killall redshift-gtk; sleep 5 && redshift-gtk &    	# redshift
pgrep -x sxhkd > /dev/null || sxhkd &                                   # hotkey daemon


# theme="forest"
# case $theme in
#     "cuts") bspc config top_padding 28; bspc config bottom_padding 28;;
#     "colorblocks") bspc config top_padding 38;;
#     "forest") bspc config top_padding 24;;
# esac


# Uncomment if you have a system tray enabled
# killall nm-applet; nm-applet &
# killall pamac-tray; pamac-tray &
# killall blueberry-tray; blueberry-tray &

# bspc monitor -d I II III IV V VI VII VIII
bspc monitor -d 1 2 3 4 5 6 7 8
# bspc monitor -d         

bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config border_width                  2
bspc config window_gap                    4
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

## COLORS
bspc config active_border_color           "#3a3e37"
bspc config focused_border_color          "#3a3e37"
bspc config normal_border_color           "#060814"  
bspc config presel_feedback_color         "#ff5f5f"

bspc config click_to_focus                none
bspc config focus_follows_pointer         true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# WS I monocle by default
# bsp-layout set monocle   
# bsp-layout set tiled 
# bsp-layout set tiled 
# bsp-layout set tiled 
# bsp-layout set tiled 
# bsp-layout set tiled 
# bsp-layout set tiled 
# bsp-layout set tiled 
# bspc desktop '^1' -l next

bsp-layout set monocle 1  
bsp-layout set tiled 2
bsp-layout set tiled 3
bsp-layout set tiled 4
bsp-layout set tiled 5
bsp-layout set tiled 6
bsp-layout set tiled 7
bsp-layout set tiled 8


# RULES

## Floating windows

# defaults
bspc rule -a *:confirm state=floating
bspc rule -a *:dialog state=floating
bspc rule -a *:download state=floating
bspc rule -a *:error state=floating
bspc rule -a *:file_progress state=floating
bspc rule -a *:notification state=floating
bspc rule -a *:splash state=floating
bspc rule -a *:toolbar state=floating
bspc rule -a *:confirmreset state=floating
bspc rule -a *:makebranch state=floating
bspc rule -a *:maketag state=floating
bspc rule -a *:branchdialog state=floating
bspc rule -a *:pinentry state=floating
bspc rule -a *:ssh-askpass state=floating

# mine
bspc rule -a *:lxpolkit state=floating
bspc rule -a *:*:'Picture in picture' state=floating
bspc rule -a *:Steam state=floating
bspc rule -a *:pavucontrol state=floating
bspc rule -a *:pulsemixer state=floating rectangle=500x250+440+275 sticky=on
bspc rule -a *:htop state=floating rectangle=900x600+233+75 sticky=on
bspc rule -a *:ncspotfloat state=floating rectangle=900x600+233+75 sticky=on
bspc rule -a *:Float state=floating
bspc rule -a *:*:Float state=floating
bspc rule -a *:emacs state=tiled
bspc rule -a *:org.pwmt.zathura state=tiled
bspc rule -a *:dragon-drag-and-drop state=floating sticky=on



## Send-to-desktop rules

# Browsers
bspc rule -a *:Navigator desktop='^1' follow=on
bspc rule -a *:qutebrowser desktop='^1' follow=on
bspc rule -a *:vivaldi-stable desktop='^1' follow=on
bspc rule -a *:brave-browser desktop='^1' follow=on
bspc rule -a *:chromium desktop='^1' follow=on

# Virtualization
bspc rule -a *:virt-manager desktop='^3' follow=on
bspc rule -a *:'VirtualBox Manager' desktop='^3' follow=on

# Games
bspc rule -a *:Steam desktop='^5' follow=on
bspc rule -a *:*:TLauncher desktop='^5' follow=on
bspc rule -a *:*:'TLauncher 2.74' desktop='^5' follow=on

# Music
bspc rule -a *:ncspot desktop='^4' follow=on
bspc rule -a *:castero desktop='^4' follow=on
bspc rule -a *:vocal desktop='^4' follow=on
bspc rule -a *:pragha desktop='^4' follow=on
bspc rule -a *:*:Spotify desktop='^4' follow=on






