#! /bin/sh

# case $(printf 'No\nYes' | dmenu -nb "#202115" -sb "#fd971f" -sf "#202115" -i -p 'Exit Qtile?') in  
case $(printf 'No\nYes' | rofi -show -dmenu -l 2 -i -p 'Exit Qtile?') in  
    Yes) qtile-cmd -o cmd -f shutdown
esac


