use_nerdfont=false
notify=true


[keybindings]
"Space" = "playpause"
"q" = "queue"
"Q" = "quit"
"w" = "sort added d"
"shift + w" = "sort added a"

[theme]
background = "#282828"
primary = "#d5c4a1"
secondary = "#689d6a"
title = "#ebdbb2"
playing = "#b16286"
playing_selected = "#282828"
playing_bg = "#3c3836"
highlight = "#282828"
highlight_bg = "#d79921"
error = "#d5c4a1"
error_bg = "#cc24id"
statusbar = "#282828"
statusbar_progress = "#fe8019"
statusbar_bg = "#98971a"
cmdline = "#d65d0e"
cmdline_bg = "#282828"
search_match = "#458588"
